### ISSUE TITLE
TODO / Roadmap

### ISSUE THREAD

**Issue by simpixelated** [simpixelated/swagger-request-maker#1]
Diff: https://github.com/simpixelated/swagger-request-maker/compare/master@%7B1day%7D...master

TODO:
- [ ] UI cleanup
  - [ ] improve response/parameter schema display
  - [ ] clean up vertical spacing
  - [ ] make all method buttons same width
- [ ] Create a request to operations defined in the [Todos API](./todos.json).
  - [ ] make param value details editable
  - [ ] save request, response, and parameter edits in state
  - [ ] persist state to local storage
- [ ] Display the response from the latest sent request.
- [ ] Make response content type dynamic / selectable
- [ ] Make schemes dynamic / selectable
- [ ] Tests
